name: Build prod

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        with:
          ref: prod
          path: source

      - name: Read phpenv-version
        id: phpenv-version
        uses: juliangruber/read-file-action@v1
        with:
          path: source/.phpenv-version

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.phpenv-version.outputs.content }}

      - name: cache npm
        uses: actions/cache@v2
        with:
          path: source/node_modules
          key: ${{ runner.os }}-${{ hashFiles('source/package-lock.json') }}

      - name: cache composer
        uses: actions/cache@v2
        with:
          path: source/vendor
          key: ${{ runner.os }}-${{ hashFiles('source/composer.lock') }}

      - name: cd setup
        run: cd source ; bin/cd-setup

      - name: purge ignored files
        run: rsync -a -c -v -z -h --exclude-from='source/.rsyncignore' source/ application

      - name: tar application
        run: tar -c -z -f application.tar application

      - name: upload application
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: application.tar
